### ISSUE TITLE
GitHub Flavored Potluck April 18 2022

### ISSUE THREAD

**Issue by raynamharris** [dib-lab/dib-lab#103]
For lab meeting in two week, I want to host a "GitHub Flavored Potluck". 

This will be a "show & tell" style meeting where everyone shares some of their favorite GitHub repositories. Like a potluck, you can share something homemade (a repo you created) or store bought (a repo someone else made). And we need all types of food, from drinks and appetizers to main dishes and desserts, so feel free to share repos big and small that serve different purposes in scientific computing, teaching, and project management. If we post links to everything thing in the chat, I'll post the chat history here and we will have a record of a lot of interesting GitHub repos. 

The goal is that we can transfer GitHub knowledge and skills and tips without having a formal "intro to GitHub" workshop and we will get to know each other a little better :)

**Comment by raynamharris** [comment]
https://happygitwithr.com/
![funwithgit](https://user-images.githubusercontent.com/7544197/163591524-8be89510-d694-41d1-b3c0-4e06ebd67ac9.png)

**Comment by ctb** [comment]
(this worked pretty well!)

**Comment by raynamharris** [comment]
Some links from the meeting:

* Zoom recording: https://us06web.zoom.us/rec/play/aKqqaLy_IB09F6MWDcun7KGxgS9okFFTohE9rtWqUQ6jOLr-VG3v9oJo2h_JB7py6ritm2x_n_UcO0mw.cZjrlIlqGnScZEa_?continueMode=true
* Zoom chat: https://hackmd.io/1vFG2KhCS0OGPED6XtLMSw
* Git for Version Control Lesson: https://swcarpentry.github.io/git-novice/
* Titus' Blog: https://github.com/ctb/titus-blog/ => https://github.com/ctb/titus-blog/
* Dib-lab website: https://github.com/dib-lab/dib-lab => [ivory.idyll.org/lab/](http://ivory.idyll.org/lab/)
* Rayna's website: https://github.com/raynamharris/raynamharris.github.io => https://www.raynamharris.com/
* Amanda's website: https://github.com/ACharbonneau/ACharbonneau.github.io => https://acharbonneau.github.io/
* A CFDE website that pulls info from 4 repos: https://github.com/nih-cfde/published-documentation/ =>  https://docs.nih-cfde.org/
* Titus Resume/CV: https://github.com/ctb/resume
* Rayna jobs: https://github.com/raynamharris/jobs
* Mo's favorite Git client: https://www.gitkraken.com/
* Daniela's fav genomics visualization tools https://hackmd.io/AUQ2E--CS3-EZqJ22mxZ0Q?view 
* GitHub for lit reviews: https://www.nature.com/articles/d41586-020-03422-x and https://github.com/paulamartingonzalez/Targeted_Literature_Reviews_via_webscraping
* Sourmash paper repo: https://github.com/dib-lab/2020-paper-sourmash-gather
* Sourmash GitHub workflows: https://github.com/sourmash-bio/sourmash/tree/latest/.github/workflows
* Tessa's blog on gh-pages integration: https://bluegenes.github.io/mkdocs-github-actions/

**Comment by mr-eyes** [comment]
Thanks, @raynamharris !
