### ISSUE TITLE
summer 2022 in person work

### ISSUE THREAD

**Issue by raynamharris** [dib-lab/dib-lab#104]
## Dates

Available

- Titus - 6/27 to 7/19

Unavailable

- Tessa - 7/10-7/14
- Jessica - 6/27 - 7/1 and 7/15 7/28

## Suggested topics

-  in-person work focusing on projects
-  preparing for teaching STAMPS
- sourmash MAGsearch / genome-grist / whatever for Antarctic cyanobacteria stuff! 
- whatever!
- whatever else!
- _please add more here!_

## Suggested locations :)

- Davis
- San Diego
- Tahoe City

![july](https://user-images.githubusercontent.com/7544197/168680993-b68f8396-ec6f-4a32-afb8-49ea2dd472c6.jpg)

**Comment by jeanzzhao** [comment]
Jean - 7/13, 7/15
