### ISSUE TITLE
spec out and buy printer

### ISSUE THREAD

**Issue by ctb** [dib-lab/dib-lab#11]

**Comment by mr-c** [comment]
fast, wifi laser color printer w/ Google Cloud Print support

**Comment by ctb** [comment]
How's this look?  I think we should get two, but we can start with one :)

http://www.amazon.com/Brother-HL-3170CDW-Digital-Wireless-Networking/dp/B00BQU141C/ref=sr_1_1?s=office-electronics&ie=UTF8&qid=1434650710&sr=1-1&refinements=p_n_feature_five_browse-bin%3A5662330011%2Cp_n_feature_six_browse-bin%3A5662334011%2Cp_n_feature_four_browse-bin%3A5928098011%2Cp_n_feature_browse-bin%3A2241305011%2C5527629011

**Comment by mr-c** [comment]
LGTM

**Comment by ctb** [comment]
Printer received!
