### ISSUE TITLE
healthy office snacks

### ISSUE THREAD

**Issue by mr-c** [dib-lab/dib-lab#18]
http://staff.ucdavis.edu/discounts/farm_fresh_flyer.pdf

http://www.farmfreshtoyou.com/

Anyone want in on this? We could start with the mini ($35/week) and move on up.

**Comment by luizirber** [comment]
Great idea, I'm in!

On Mon, Jun 22, 2015 at 7:39 PM, Michael R. Crusoe <notifications@github.com

**Comment by ctb** [comment]
I can kick in $5 (a week)

**Comment by mr-c** [comment]
Ordered. Since delivery to the office is only offered on Fridays I opted to have it delivered to my house and will bring it in next Tuesday.

**Comment by ctb** [comment]
Ping us when $$ req, pls!

**Comment by mr-c** [comment]
I'm tracking payments at https://docs.google.com/spreadsheets/d/1yFOVjXvgayX1Z9fm9IwUNYEZXfFt8S9oorqGHlaP9Yc/edit?usp=sharing

**Comment by mr-c** [comment]
@ctb we have the option of customizing each delivery: https://drive.google.com/file/d/10WwzzKSIiGfvab_OQA2A-eEMyllfGn_UqzBkiO71VEMicRVbcTXd40DELhRBjpVR9yL_-HZbBi010B5B/view?usp=sharing

Let me know if you have any suggestions.
