### ISSUE TITLE
Purchases for the week of June 22nd

### ISSUE THREAD

**Issue by mr-c** [dib-lab/dib-lab#19]
Mini DisplayPort to DisplayPort Cable
$7
http://www.amazon.com/gp/product/B0034X6SCY

**Comment by ctb** [comment]
Index cards:
http://www.amazon.com/Oxford-Index-Assorted-Colors-100-Pack/dp/B000EFNKLC/ref=sr_1_2?ie=UTF8&qid=1435082657&sr=8-2&keywords=big+index+cards

**Comment by ctb** [comment]
2 of these: http://www.amazon.com/Post--Command-Strips-23-Inches-20-Sheets/dp/B0000E2RGR/ref=sr_1_1?ie=UTF8&qid=1435082684&sr=8-1&keywords=wall+sticky+notes

**Comment by mr-c** [comment]
lock anchors http://www.amazon.com/Desktop-lock-Anchors-two-piece/dp/B00FP11J6I

**Comment by ctb** [comment]
Also some nice screen wipes - maybe in individual packets? http://www.amazon.com/Dust-Off-Touch-Screen-Individual-Packets/dp/B00N3AQ1LQ

**Comment by mr-c** [comment]
This cable so I can use the Chromebox with the mac monitor: http://www.amazon.com/StarTech-com-DP2MDPMF6IN-DisplayPort-Video-Adapter/dp/B003N3DTKY

**Comment by mr-c** [comment]
Who is sending this list to Jason?

**Comment by ctb** [comment]
On Fri, Jun 26, 2015 at 02:00:52PM -0700, Michael R. Crusoe wrote:

> Who is sending this list to Jason?

I'll send it over the weekend or on Monday; feel free to send it before
then.

**Comment by ctb** [comment]
Laser printer paper, e.g.

http://www.amazon.com/HP-11310-0-Premium-Choice-Laserjet/dp/B000099O2W/ref=lp_1069724_1_1?s=office-products&ie=UTF8&qid=1435361155&sr=1-1

**Comment by ctb** [comment]
Asked Jason to order:

1 x http://www.amazon.com/gp/product/B0034X6SCY
1 x http://www.amazon.com/Oxford-Index-Assorted-Colors-100-Pack/dp/B000EFNKLC/ref=sr_1_2?ie=UTF8&qid=1435082657&sr=8-2&keywords=big+index+cards
2 x http://www.amazon.com/Post--Command-Strips-23-Inches-20-Sheets/dp/B0000E2RGR/ref=sr_1_1?ie=UTF8&qid=1435082684&sr=8-1&keywords=wall+sticky+notes
3 x http://www.amazon.com/Desktop-lock-Anchors-two-piece/dp/B00FP11J6I
1 x http://www.amazon.com/Dust-Off-Touch-Screen-Individual-Packets/dp/B00N3AQ1LQ
1 x http://www.amazon.com/StarTech-com-DP2MDPMF6IN-DisplayPort-Video-Adapter/dp/B003N3DTKY

If we don’t have an easy local source for printer paper,

2 x http://www.amazon.com/HP-11310-0-Premium-Choice-Laserjet/dp/B000099O2W/ref=lp_1069724_1_1?s=office-products&ie=UTF8&qid=1435361155&sr=1-1
