### ISSUE TITLE
github private repos

### ISSUE THREAD

**Issue by ctb** [dib-lab/dib-lab#28]
I'd be happy to pay github for some more private repos, for people who aren't quite ready to be ridiculously open yet and/or want to get started on a project without having it be in public view.
I was thinking in particular that @drtamermansour stuff from lab meeting would be a good fit. Thoughts?

Right now we have 3 free ones, I think.

**Comment by luizirber** [comment]
Free access to five private repos with GitHub Education; https://education.github.com/
If we want lab-level control and access for private repos they have a discount for organizations, but I think it is only for classrooms.

**Comment by ctb** [comment]
On Wed, Jun 24, 2015 at 11:47:14AM -0700, Luiz Irber wrote:

> Free access to five private repos with GitHub Education; https://education.github.com/
> If we want lab-level control and access for private repos they have a discount for organizations, but I think it is only for classrooms.

OK, fine, whatever, we have 5 private repos. One or two are already in use.
Do we want more? :)

Tell ya what: if you want a private repo, let me or @mr-c know and we'll
figure it out.
