### ISSUE TITLE
Prepare for Moore Foundation site visit.

### ISSUE THREAD

**Issue by ctb** [dib-lab/dib-lab#44]
After lunch on Tuesday, Sep 15, the Moore Foundation folk (@strasser and @cmentzel, probably) will come by the lab for about three hours to hear about what we're doing.  We should probably plan on telling them something :)

First hour: I'll give an overview / etc
Second hour: presentations by folk
Third hour: Challenges, opportunities, and "other stuff" - specifically, "What problems have you encountered (scientific, recruiting, recognition etc.)? What new methods or advances are you exploring? What interesting work are you watching?" -- tracked in #43.

For the second hour, I'd like to encourage everyone to come up with one thing to talk about for no more than 5 minutes, with 1 slide OR a brief demo. Suggestions:
- @camillescott - literate data analysis in notebooks, => pweave
- @mr-c - building a community around contributing to software
- @schwarzem - conserved unknowns (scoring approach) OR "weird stuff in metagenomes"
- @ljcohen - nanopore plans OR MMETSP
- @jessicamizzi - ?? not sure, but maybe a report on week3?
- @drtamermansour - horses! or dogs!
- @SherineAwad - all metagenome assemblers do the same thing, what?
- @luizirber - not sure, what do you suggest? HLL?

I'd also like to see if I can get someone to touch on "science code" session; what am I missing? (We can have some people go twice as long as its on wildly different things.)

Update: also, khmer-protocols? streaming? & sketches?

I asked for some guidance on the site visit intensity:

```
  On a scale from 1-10, ranging from 1 ("shoot me now") to 10 ("wait,
  is someone actually shooting at me?") how exciting would you like your Davis
  site visit to be?
```

and the response was "a 6 or a 7" so plan accordingly!

**Comment by ctb** [comment]
@luizirber - maybe "Streaming is awesome"?

**Comment by camillescott** [comment]
You're gonna have to clarify how that intensity scale works, 'cause currently I've got _no_ idea what that's supposed to mean :)

**Comment by ctb** [comment]
On Mon, Aug 31, 2015 at 02:46:04PM -0700, Camille Scott wrote:

> You're gonna have to clarify how that intensity scale works, 'cause currently I've got _no_ idea what that's supposed to mean :)

It's probably linear. Does that help?

**Comment by tracykteal** [comment]
I can speak to 'demand for training' :) Maybe in the third hour or over lunch?

**Comment by drtamermansour** [comment]
I would present the horse transcriptome as an example of a collaborative platform to enhance functional genomics.

**Comment by SchwarzEM** [comment]
On Aug 31, 2015, at 5:26 PM, C. Titus Brown wrote:

> For the second hour, I'd like to encourage everyone to come up with one thing to talk about for no more than 5 minutes, with 1 slide OR a brief demo. Suggestions:
> 
>   • @camillescott - literate data analysis in notebooks, => pweave
>   • @mr-c - building a community around contributing to software
>   • @schwarzem - conserved unknowns (scoring approach) OR "weird stuff in metagenomes"
>   • @ljcohen - nanopore plans OR MMETSP
>   • @jessicamizzi -
>   • @drtamermansour - horses! or dogs!
>   • @SherineAwad - all metagenome assemblers do the same thing, what?
>   • @luizirber - not sure, what do you suggest? HLL?

```
I can talk about "weird stuff in metagenomes".

I assume that the scale "1 == shoot me now" means amped-up intensity and "10 == is somebody shooting at me?" means somnolent torpor, so hitting a 6/7 should be doable.
```

--Erich

**Comment by drtamermansour** [comment]
Actually I am not sure what @ctb means by "Exiting". I think this means what are the far objectives and how crazy we would go to achieve it.

**Comment by cmentzel** [comment]
I am totally confused as to what "intensity"means and the strange scale...  Are we talking about technical/scientific detail?  Perhaps good for you all to know that none of us from Moore are as expert in your science or technology stack as you are, so using the English language and defining your jargon (though less efficient for you) to describe what you are doing will be very much appreciated.

**Comment by cmentzel** [comment]
Also, it will be @strasser, @cmentzel (me), and Mark Stalzer (former Data Science Fellow @ moore) on the site visit.

**Comment by ctb** [comment]
OK, folks, the lab exercise to demonstrate how hard it is to communicate clearly is now OVER. Back to our high-functioning routine!

---

Slightly more seriously, thanks for the reminder about tech talk @cmentzel. We'll see what we can do.

From my perspective, I'd rather be shot than sit through a boring lecture, and people shooting at me (so far only in paintball) proves to be rather adrenalin inducing.  Since no one seems to get my intensity scale other than @strasser, let's just say that long, detail-filled Powerpoint slides are a no-no and we should strive to be entertaining, informative, and at least somewhat provocative.

Given that we're also supposed to communicate clearly and also not take very long, this should be fun!

Hmm, maybe think Ignite-style talks? http://scottberkun.com/2009/how-to-give-a-great-ignite-talk/

**Comment by cmentzel** [comment]
or, I dont know, perhaps very minimal ppts/html presos, and more discussion and/or demos.  Up to you all (and of course @strasser), dont want to prescribe too much, or make things more stressful than necessary.  You may have already expended the amount of pre-planning effort we were expecting.  I assume you all know what you are working on, we just want to know what that is... 

from the FAQ (https://github.com/DDD-Moore/investigators/blob/master/2015_site_visit.md):

> **What do I and my lab members need to prepare?** We would like this to be more of a discussion, rather than a series of presentations- please use minimal slides. We would love demos of your work, if appropriate! You should not need to spend an extensive amount of time preparing for this visit. If there are problems, challenges, or opportunities that we can discuss with you, we would welcome the opportunity to learn more about these themes, and possibly even explore solutions with you. In the third hour, we would like to hear from you about your more speculative, future facing work, new methods or advances on the horizon.

**Comment by ctb** [comment]
_shrug_ since we haven't started up regular lab meetings (the lab only assembles at Davis collectively next week, and we're still missing 2.5 postdocs that will be starting soon) I don't think anyone other than maybe me has any handle at all on what we're working on.  So this is a good opportunity to coordinate!

**Comment by cmentzel** [comment]
[Wunderbar](https://en.wiktionary.org/wiki/wunderbar)

**Comment by ctb** [comment]
Camille: literate bioinformatics
Tamer: summarizing multiple mRNAseq; building “a” pipeline.
Erich: phylogenetically conscious metagenomics
Sherine: does assembly work
Lisa: MMETSP (after Camille, Tamer, Erich)
Qingpeng: IGS
Jessica: week3
Erich: conserved unknown
Lisa: nanopore
Luiz: streaming and sketches
Camille: scihack
