### ISSUE TITLE
Lunch orders for the Moore Foundation site visit

### ISSUE THREAD

**Issue by ctb** [dib-lab/dib-lab#46]
Hi all,

we'll be meeting at Zen Toro Sushi at ~11:45am on Tuesday, Sep 15. The reservation is under "Titus."

They'd like orders by tomorrow morning.

Choose from the lunch menu and/or sushi roll menu: http://www.zentorosushi.com/menu/.  Order reasonably, please ;).

If you are up for "sushi and/or sashimi" we can order a sushi boat, so just let me know if that's your order.

cc @tracykteal @jessicamizzi @luizirber @qingpeng @camillescott @mr-c @SherineAwad @drtamermansour @ljcohen

**Comment by johnsolk** [comment]
+1 for "sushi and/or sashimi"

**Comment by SchwarzEM** [comment]
I'd like Grilled Atlantic Salmon Fillet, with teriyaki.

**Comment by camillescott** [comment]
Tapas Roll + spicy tuna roll for me

On Mon, Sep 14, 2015 at 12:53 PM, ljcohen notifications@github.com wrote:

> +1 for "sushi and/or sashimi"
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dib-lab/dib-lab/issues/46#issuecomment-140188635.

## 

Camille Scott

Department of Computer Science
Lab for Data Intensive Biology
University of California, Davis

camille.scott.w@gmail.com

**Comment by SherineAwad** [comment]
Chicken Teriyaki please.

**Comment by mr-c** [comment]
Mixed sashimi please.

**Comment by jessicalumian** [comment]
sushi and/or sashimi, I'm not picky. Thanks!

**Comment by luizirber** [comment]
Noodle and sushi combination - beef soba with spicy chicken teriyaki roll

**Comment by ctb** [comment]
Address:

132 E Street, Suite 100
Davis, CA — 95616
(530) 753-0154

**Comment by drtamermansour** [comment]
I will go with Chicken teriyaki please

Thanks
Tamer

**Comment by qingpeng** [comment]
Chicken teriyaki please.

**Comment by tracykteal** [comment]
lunch and sushi combo please, with shrimp tempura and spicy tuna roll

**Comment by ctb** [comment]
Ordered!
