### ISSUE TITLE
2015-09-28 lab meeting (Monday)

### ISSUE THREAD

**Issue by ctb** [dib-lab/dib-lab#54]
@drtamermansour presenting, 1-3pm, on horse transcriptome work, I believe.

**Comment by camillescott** [comment]
Have we changed the day?

On Mon, Sep 21, 2015 at 5:00 PM, C. Titus Brown notifications@github.com
wrote:

> @drtamermansour https://github.com/drtamermansour presenting, 1-3pm, on
> horse transcriptome work, I believe.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dib-lab/dib-lab/issues/54.

## 

Camille Scott

Department of Computer Science
Lab for Data Intensive Biology
University of California, Davis

camille.scott.w@gmail.com

**Comment by ctb** [comment]
Just for this meeting, yes.  It was discussed in the meeting and I confirmed
with Tamer.
