### ISSUE TITLE
2015-10-7 Lab meeting

### ISSUE THREAD

**Issue by johnsolk** [dib-lab/dib-lab#58]
Presenter: Lisa

**Comment by ctb** [comment]
Note, @camillescott and I will be absent - we're going to the Moore DDD symposium in seattle. Apologies!

**Comment by johnsolk** [comment]
https://docs.google.com/a/ucdavis.edu/presentation/d/1vsuKsP8S_5kZqyvPsVLtgg8YiNphHubhSOi6snPb2t4/edit?usp=sharing
