### ISSUE TITLE
2015-21-15 Lab Meeting (Jessica)

### ISSUE THREAD

**Issue by jessicalumian** [dib-lab/dib-lab#60]
Working Title-

Eel Pond Protocols: An Ode to Project Based Learning

**Comment by ctb** [comment]
lol

**Comment by ctb** [comment]
Pre-ode topics:
- sofa update
- fika update

Topics for post-ode, should there be time:
- alternative things we should be doing wrt training than running 2-day workshops - thoughts?
- dear abby column
- buoy use case discussions??
- open science prize??

**Comment by jessicalumian** [comment]
3p Tu Thurs Fika
