### ISSUE TITLE
Meeting to discuss the lab focus

### ISSUE THREAD

**Issue by drtamermansour** [dib-lab/dib-lab#65]
Suggestion: Tomorrow after Fika

**Comment by ctb** [comment]
On Wed, Oct 28, 2015 at 03:31:13PM -0700, Tamer Mansour wrote:

> Suggestion: Tomorrow after Fika   

I have Rachel Whitaker's talk at 4:10pm, so "after fika" would be too short.

Alternatively, we could move the fika forward to 2:30.  Or just use the
fika to talk about it.
