### ISSUE TITLE
2015-12-09 Lab Meeting Jessica

### ISSUE THREAD

**Issue by jessicalumian** [dib-lab/dib-lab#72]
In which I will explain why the graphs I showed you last time I presented are bs (along with corrected graphs!), and pitch our crazy training plans for the next two quarters.

Starting at 1pm PST

**Comment by ctb** [comment]
did you annc => dibl?

**Comment by drtamermansour** [comment]
I suggest starting an issue where you discuss your plans for the assembly/variant calling project (or an email like the one Eric send about the denovo assembly).

**Comment by jessicalumian** [comment]
I will create that, thanks for the idea.
