### ISSUE TITLE
2016-06-06 Lab Party hosted by Jessica!!

### ISSUE THREAD

**Issue by jessicalumian** [dib-lab/dib-lab#76]
Just kidding - it is only a lab meeting. I will talk about - 
- de novo tule elk genome assembly + snp calling 
- eel pond (de novo transcriptome assembly w/ nematostella data) streaming vs non streaming benchmarking results 

Starting time 1:15 pm PST

**Comment by ctb** [comment]
links to slides?

**Comment by jessicalumian** [comment]
https://docs.google.com/presentation/d/18JVhoAfEtMXlPQ1BMEZSi7kN6YEFCvz54tzdTQIgcjQ/edit?usp=sharing
